export enum InputType {
    BUTTON = 'button',
    CHECKBOX = 'checkbox',
    EMAIL = 'email',
    COLOR = 'color',
    DATE = 'date',
    FILE = 'file',
    HIDDEN = 'hidden',
    IMAGE = 'image',
    MONTH = 'month',
    NUMBER = 'number',
    PASSWORD = 'password',
    RADIO = 'radio',
    RANGE = 'range',
    RESET = 'reset',
    SEARCH = 'search',
    TEL = 'tel',
    TEXT = 'text',
    TIME = 'time',
    URL = 'url',
    WEEK = 'week',
    DATETIME_LOCAL = 'datetime-local',
    SUBMIT = 'submit'
}