export enum Icons {
    DOWN = 'down',
    HUMBURGER = 'hum-menu',
    HUMBURGER_SHORT = 'hum-menu-short',
    LOGO = 'logo',
    PROFILE = 'profile',
    ARCHITECTURE = 'architecture',
    ATTACH = 'attach',
    BOOKMARK = 'bookmark',
    CHAT = 'chat',
    CODE = 'code',
    DARK_THEME = 'dark',
    LIGHT_THEME = 'light',
    DELETE = 'delete',
    DOT = 'dot',
    EDIT = 'edit',
    ENGINEER = 'engineer',
    EXCLAMATION = 'exclamation',
    HEART = 'heart',
    LIST = 'list',
    LOGIN = 'login',
    MUSIC = 'music',
    OPTIONS = 'options',
    PAINTER = 'painter',
    PHOTO = 'photo',
    PLUS = 'plus',
    SEARCH = 'search',
    SEND = 'send',
    VIDEO = 'video',
    WEB_DESIGN = 'web-design',
    WINK = 'wink',
    
}
//eye, eye-icon, gallery, google, logo-full, ok-logo, telegram-logo, vk-logo, 