export class FeedTestData {
    static Albums = [
        {
            albumCover: "/assets/testCovers/img-1.jpg",
            username: "Аркокий Лефидров",
            views: 15352,
            likes: 3752,
            isBookmark: false,
            isLiked: true,
            desc: "Ex aute tempor sint eiusmod duis sint eu consequat eu officia ut. Aliquip excepteur do nulla eu magna sunt nostrud Lorem. Labore nostrud duis cupidatat ipsum cillum consectetur ex anim proident.",           title: "Самый лучший в мире альбом",
        },
        {
            albumCover: "/assets/testCovers/img-2.jpg",
            username: "Аркадий Алфёров",
            avatar: "/assets/testAvatars/ava-2.jpg",
            views: 1278,
            likes: 543,
            isBookmark: true,
            isLiked: false,
            desc: "Ex aute tempor sint eiusmod duis sint eu consequat eu officia ut. Aliquip excepteur do nulla eu magna sunt nostrud Lorem. Labore nostrud duis cupidatat ipsum cillum consectetur ex anim proident.",
            title: "Тоже самый лучший в мире альбом",
        },
        {
            albumCover: "/assets/testCovers/img-3.jpg",
            username: "Пёс Киберпанков",
            avatar: "/assets/testAvatars/ava-3.png",
            views: 127537,
            likes: 548632,
            isBookmark: true,
            isLiked: true,
            desc: "Ex aute tempor sint eiusmod duis sint eu consequat eu officia ut. Aliquip excepteur do nulla eu magna sunt nostrud Lorem. Labore nostrud duis cupidatat ipsum cillum consectetur ex anim proident.",
            title: "Самый самый лучший в мире альбом",
        },
        {
            albumCover: "/assets/testCovers/img-1.jpg",
            username: "Аркокий Лефидров",
            views: 15352,
            likes: 3752,
            isBookmark: false,
            isLiked: true,
            desc: "Ex aute tempor sint eiusmod duis sint eu consequat eu officia ut. Aliquip excepteur do nulla eu magna sunt nostrud Lorem. Labore nostrud duis cupidatat ipsum cillum consectetur ex anim proident.",           title: "Самый лучший в мире альбом",
        },
        {
            albumCover: "/assets/testCovers/img-2.jpg",
            username: "Аркадий Алфёров",
            avatar: "/assets/testAvatars/ava-2.jpg",
            views: 1278,
            likes: 543,
            isBookmark: true,
            isLiked: false,
            desc: "Ex aute tempor sint eiusmod duis sint eu consequat eu officia ut. Aliquip excepteur do nulla eu magna sunt nostrud Lorem. Labore nostrud duis cupidatat ipsum cillum consectetur ex anim proident.",
            title: "Тоже самый лучший в мире альбом",
        },
        {
            albumCover: "/assets/testCovers/img-3.jpg",
            username: "Пёс Киберпанков",
            avatar: "/assets/testAvatars/ava-3.png",
            views: 127537,
            likes: 548632,
            isBookmark: true,
            isLiked: true,
            desc: "Ex aute tempor sint eiusmod duis sint eu consequat eu officia ut. Aliquip excepteur do nulla eu magna sunt nostrud Lorem. Labore nostrud duis cupidatat ipsum cillum consectetur ex anim proident.",
            title: "Самый самый лучший в мире альбом",
        },
        {
            albumCover: "/assets/testCovers/img-1.jpg",
            username: "Аркокий Лефидров",
            views: 15352,
            likes: 3752,
            isBookmark: false,
            isLiked: true,
            desc: "Ex aute tempor sint eiusmod duis sint eu consequat eu officia ut. Aliquip excepteur do nulla eu magna sunt nostrud Lorem. Labore nostrud duis cupidatat ipsum cillum consectetur ex anim proident.",           title: "Самый лучший в мире альбом",
        },
        {
            albumCover: "/assets/testCovers/img-2.jpg",
            username: "Аркадий Алфёров",
            avatar: "/assets/testAvatars/ava-2.jpg",
            views: 1278,
            likes: 543,
            isBookmark: true,
            isLiked: false,
            desc: "Ex aute tempor sint eiusmod duis sint eu consequat eu officia ut. Aliquip excepteur do nulla eu magna sunt nostrud Lorem. Labore nostrud duis cupidatat ipsum cillum consectetur ex anim proident.",
            title: "Тоже самый лучший в мире альбом",
        },
        {
            albumCover: "/assets/testCovers/img-3.jpg",
            username: "Пёс Киберпанков",
            avatar: "/assets/testAvatars/ava-3.png",
            views: 127537,
            likes: 548632,
            isBookmark: true,
            isLiked: true,
            desc: "Ex aute tempor sint eiusmod duis sint eu consequat eu officia ut. Aliquip excepteur do nulla eu magna sunt nostrud Lorem. Labore nostrud duis cupidatat ipsum cillum consectetur ex anim proident.",
            title: "Самый самый лучший в мире альбом",
        },
        {
            albumCover: "/assets/testCovers/img-1.jpg",
            username: "Аркокий Лефидров",
            views: 15352,
            likes: 3752,
            isBookmark: false,
            isLiked: true,
            desc: "Ex aute tempor sint eiusmod duis sint eu consequat eu officia ut. Aliquip excepteur do nulla eu magna sunt nostrud Lorem. Labore nostrud duis cupidatat ipsum cillum consectetur ex anim proident.",           title: "Самый лучший в мире альбом",
        },
        {
            albumCover: "/assets/testCovers/img-2.jpg",
            username: "Аркадий Алфёров",
            avatar: "/assets/testAvatars/ava-2.jpg",
            views: 1278,
            likes: 543,
            isBookmark: true,
            isLiked: false,
            desc: "Ex aute tempor sint eiusmod duis sint eu consequat eu officia ut. Aliquip excepteur do nulla eu magna sunt nostrud Lorem. Labore nostrud duis cupidatat ipsum cillum consectetur ex anim proident.",
            title: "Тоже самый лучший в мире альбом",
        },
        {
            albumCover: "/assets/testCovers/img-3.jpg",
            username: "Пёс Киберпанков",
            avatar: "/assets/testAvatars/ava-3.png",
            views: 127537,
            likes: 548632,
            isBookmark: true,
            isLiked: true,
            desc: "Ex aute tempor sint eiusmod duis sint eu consequat eu officia ut. Aliquip excepteur do nulla eu magna sunt nostrud Lorem. Labore nostrud duis cupidatat ipsum cillum consectetur ex anim proident.",
            title: "Самый самый лучший в мире альбом",
        },
    ];
}